### ISSUE TITLE
Oasis message event handlers are not run in run loop for ember apps

### ISSUE THREAD

**Issue by hjdivad** [tildeio/oasis.js#12]

**Comment by stefanpenner** [comment]
:+1: https://github.com/yapplabs/glazier/commit/4ac46474d4f5314253494145a8b0a7692bc9cb38

**Comment by hjdivad** [comment]
@stefanpenner  woot.  Let me know if you notice that I missed a spot.

**Comment by stefanpenner** [comment]
sgb
