### ISSUE TITLE
Dangling promises 

### ISSUE THREAD

**Issue by stefanpenner** [tildeio/oasis.js#18]
https://github.com/tildeio/oasis.js/blob/master/lib/oasis/connect.js#L16-L18
https://github.com/tildeio/oasis.js/blob/master/lib/oasis/sandbox.js#L43-L46
https://github.com/tildeio/oasis.js/blob/master/lib/oasis/message_channel.js#L123
https://github.com/tildeio/oasis.js/blob/master/lib/oasis/sandbox.js#L134-L137
# yuleavemehangingbreaux

**Comment by hjdivad** [comment]
scumbag @hjdivad
