### ISSUE TITLE
iframes should be able to be created with allow-popup (conditionally?)

### ISSUE THREAD

**Issue by lukemelia** [tildeio/oasis.js#4]
In https://github.com/tildeio/oasis.js/blob/master/lib/oasis.js#L52, the iframe sandbox is set to "allow-same-origin allow-scripts". For cards that should be allowed to consume APIs on their own, it will be valuable for them to be able to open a popup window to perform OAuth.

This can be enabled by adding `allow-popups` to the sandbox value. I'm not sure what the best way to make this configurable is. Perhaps this is something that conductor would decide about at installation time?

**Comment by hjdivad** [comment]
This feels like a capability that happens not to be fulfilled by a service.  It seems reasonable for a containing environment to want to create multiple cards, but only allow some of them to create popups.

**Comment by lukemelia** [comment]
In actually working through an OAuth process, it appears that the window that is opened inherits the sandbox restrictions of the iframe (which is great), however this means that I also need the `allow-forms` permission.

**Comment by lukemelia** [comment]
Agreed re: containing environment having varying levels of trust/permissions for different cards.

**Comment by hjdivad** [comment]
One downside of expressing this as a capability is it will share a namespace with user-defined services.

This might be okay: we can just reserve certain capability names (eg `allowPopups`) from spec.  But it might be nice to carve out a whole namespace with a convention (eg `conductor:allowPopups`).

**Comment by cyril-sf** [comment]
The authentication capability is used as an example in the spec

http://www.w3.org/html/wg/wiki/ChangeProposals/sandbox_allow_popups#APPENDIX_A

> We have several Web App scenarios where sandboxed code needs to be able to pop-out windows/forms from the  host app, as well as certain authentication scenarios where sandboxed code needs to be able to pop-out an  authentication window so the URL can be validated by the end user before credentials are entered

**Comment by cyril-sf** [comment]
Internet Explorer 10 seems to support `ms-allow-popups` instead of `allow-popups`

http://msdn.microsoft.com/en-us/hh563496.aspx

> ms-allow-popups
> Sometimes it is useful to allow embedded content opening up new popup windows. A perfect example is a mapping service like Bing Maps.
> 
> When embedding Bing Maps, additional functionality like driving directions or destination details can be looked up in popup windows. But since sandbox prohibits this, there’s a setting in Internet Explorer 10 that will enable popups without compromising the sandbox.
> 
> The following code shows how to set up ms-allow-popups.
> 
> When setting this value, embedded sites are able to display information in a new window.

Internet Explorer 8 and 9 are not supported.

**Comment by cyril-sf** [comment]
Firefox doesn't support yet `allow-popups`

https://bugzilla.mozilla.org/show_bug.cgi?id=766282

**Comment by cyril-sf** [comment]
The lack of cross browsers support mean we will probably have to rely on an iframe with an origin to currently support this feature.
