### ISSUE TITLE
<base> shouldn't be injected on iframe adapter

### ISSUE THREAD

**Issue by bkardell** [tildeio/oasis.js#62]
At least... I think not.  This caused me some amount of confusion as urls I used switched base midway through... I could make an xhr request while the page was loading for "x.json" but if I sent a message asking the child window to do it for me and the child window used a relative url, I would get errors.

For iframes that provide services, this seems really unintuitive.  

I'm still getting into the code itself, so it's not exactly clear to me how best you'd skip this.  The simplest thing seems to be to wrap an if as below:

// in connectSandbox:
if (adapter.type !== 'html') {
   adapter.loadScripts(event.data.base, event.data.scriptURLs);
}

But it doesn't seem you have the information handy.  After poking around a few minutes I found you could mark this upstream as below...

// in initializeSandbox
if (window.parent && window.parent !== window) {
   iframeAdapter.type = "html";
   iframeAdapter.connectSandbox(ports);
}

That doesn't seem ideal to me since this is specified in the original configuration I used to create it already - not available?  

Am I offbase? Do we really want to be setting base on iframes?  If so, why?

**Comment by hjdivad** [comment]
We should definitely fix this, although I think we want to set `<base>` for JavaScript sandboxes as the sandbox may be at a different path than the bootstrap.

But for HTML sandboxes it does not make sense to inject a `<base>` tag.

**Comment by hjdivad** [comment]
I think when we send the initial initialisation message, where we know the requested sandbox type, we should simply not include a base attribute.  Then the sandbox side can simply skip base if it's not provided.

**Comment by hjdivad** [comment]
All iframe sandboxes are now HTML, so we're not injecting base at all.  The JavaScript sandbox in iframe adapter approach added a lot of complexity for not enough win.
